[project]
name = "llm-macro-lib-idea"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llm>=0.26",
    "llm-openrouter>=0.4.1",
    "pydantic>=2.11.7",
    "pypdf>=5.9.0",
]
